version: "2.4"

services:
  blackend-fe:
    build:
       context: frontend/
       dockerfile: Dockerfile
    ports:
      - "3000:80"

  blackend-ms:
    build:
       context: mock-server/
       dockerfile: Dockerfile
    ports:
      - "3001:3001"
