apiVersion: v1
kind: Pod
metadata:
  name: dind
  namespace: jenkins
spec:
  serviceAccountName: jenkins
  containers:
  - name: docker
    image: docker:dind
    args:
      - dockerd
      - --storage-driver=overlay2
      - -H unix:///var/run/docker.sock
      - -H tcp://0.0.0.0:2375
    tty: true
    securityContext:
      privileged: true
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: DOCKER_HOST
      value: tcp://localhost:2375
    - name: DOCKER_USERNAME
      valueFrom:
        secretKeyRef:
          name: acr-auth
          key: username
    - name: DOCKER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: acr-auth
          key: password
    volumeMounts:
      - name: dind-storage
        mountPath: /var/lib/docker
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "2Gi"
        cpu: "500m"
  - name: kubectl
    image: sourcery2019fall.azurecr.io/helm:v3.0.0-rc.1
    command: ["kubectl"]
    args: ["get", "pods", "--watch"]
  volumes:
    - name: dind-storage
      hostPath:
        path: /dockerbuilds/builds/dblackend-fe
        type: DirectoryOrCreate
